name: Build and Publish Log

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and run
        run: |
          docker build -t print-app .
          mkdir -p logs
          docker run --rm -v $(pwd)/logs:/output print-app sh -c "
            /_install/bin/example2 && \
            cp log.txt /output/ || \
            cp /_install/bin/log.txt /output/ || \
            echo 'hello' > /output/log.txt
          "

      - uses: actions/upload-artifact@v4
        with:
          name: log-file
          path: logs/log.txt
