name: Build and Publish Log

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build in Docker
      run: |
        docker build -t print-app .
        mkdir -p logs
        docker run --rm -v $(pwd)/logs:/home/logs print-app /_install/bin/example2

    - name: Upload log as artifact
      uses: actions/upload-artifact@v2
      with:
        name: log-file
        path: logs/log.txt
